# Generated by cpp11: do not edit by hand

libproj_cpp_version <- function() {
  .Call(`_libproj_libproj_cpp_version`)
}

libproj_cpp_has_libtiff <- function() {
  .Call(`_libproj_libproj_cpp_has_libtiff`)
}

libproj_cpp_has_libcurl <- function() {
  .Call(`_libproj_libproj_cpp_has_libcurl`)
}

libproj_cpp_cleanup <- function() {
  invisible(.Call(`_libproj_libproj_cpp_cleanup`))
}
